- hosts: app
  become: true
  collections:
    - community.docker

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_host: unix:///var/run/docker.sock

  tasks:
    # -------------------------
    # SYSTEM SETUP
    # -------------------------
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker.io
          - python3-pip
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # -------------------------
    # DOCKER SDK
    # -------------------------
    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    # -------------------------
    # APPLICATION DEPLOYMENT
    # -------------------------
    - name: Pull Secret Message Locker image
      community.docker.docker_image:
        name: mikassaa/secret-message-locker
        tag: latest
        source: pull
        docker_host: "{{ docker_host }}"

    - name: Run Secret Message Locker container
      community.docker.docker_container:
        name: secret-message-app
        image: mikassaa/secret-message-locker:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        env:
          SUPABASE_URL: "{{ supabase_url }}"
          SUPABASE_ANON_KEY: "{{ supabase_anon_key }}"
          MASTER_KEY: "{{ master_key }}"
          NEXT_PUBLIC_HOST: "{{ next_public_host }}"
        docker_host: "{{ docker_host }}"
        
